spring:
  datasource:
    url: jdbc:mysql://192.168.227.129:3306/workorderms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: xiaoming
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      initial-size: 5
      max-active: 5
      min-idle: 5

server:
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  tomcat:
    uri-encoding: UTF-8
